#!/bin/sh
#turbo ipv6, update DNS when l2tp-ipv6 interface is up or down
# For lots of DNS server is "dirty", which lead us get wrong ip/ipv6 target and cannot
# access correct resource. So only use correct DNS if l2tp-ipv6 is up
# restore DNS if l2tp-ipv6 is down
#

ifname_ipv6="ipv6"

[ "$INTERFACE" != "$ifname_ipv6" -o "$ACTION" = "ifupdate" ] && exit 0


. /lib/functions.sh
. /lib/functions/network.sh

[ "$ACTION" = "ifup" ] && {
    ubus call turbo_ipv6 event_update '{"event":"connected"}' >/dev/null 2>&1
}


[ "$ACTION" = "ifdown" ] && {
    ubus call turbo_ipv6 event_update '{"event":"disconnected"}' >/dev/null 2>&1
}

