#!/bin/sh /etc/rc.common

START=99
STOP=20

#export command line for /usr/sbin/supervisord

USB_DEPLOY_ROOT_PATH=$1

if [ -n "$USB_DEPLOY_ROOT_PATH" ];then
  export PROCLINE="$USB_DEPLOY_ROOT_PATH/xiaomi_router/bin/mediaservice"
  export PROC_USE_CGROUP_PATH="/dev/cgroup/mem/group1/tasks"
  export PROC_EXT_LIB_PATH="$USB_DEPLOY_ROOT_PATH/xiaomi_router/lib"
  export PROC_FAST_REBOOT="1"
else
  export PROCLINE="/usr/sbin/mediaservice"
  export PROC_USE_CGROUP_PATH="/dev/cgroup/mem/group1/tasks"
fi

export EXTRA_COMMANDS="status start_impl"

start_impl() {
	#处理一部分data文件夹没有写权限的问??
	#chmod 777 /userdisk/data

  /usr/sbin/supervisord start
  return $?
}

start ()
{
  appid=2882303761517281003
  file=/userdisk/appdata/app_infos/$appid.manifest 
  if [ -f "$file" ]
  then
    on=5;
    off=6;
    status=`sed -n '/^status/s/.*\"\(.*\)\".*/\1/pg' $file` 
    if [ -n "$status" ]
    then
      if [ "$status" = "$on" ] 
      then
        ret=1
        if [ ! -f /userdisk/appdata/MitvOrMiboxHasConnectedRouter ]
        then
          ret=0
          touch /userdisk/appdata/MitvOrMiboxHasConnectedRouter 

          result=`curl localhost:/cgi-bin/luci/api/xqsystem/sdev|xargs`
          field_left=`echo $result|sed  -n 's/{\(.*\),\(.*\),\(.*\)}/\1/gp'  |grep -v code|awk -F: '{print $2}'`
          field_center=`echo $result|sed  -n 's/{\(.*\),\(.*\),\(.*\)}/\2/gp'  |grep -v code|awk -F: '{print $2}'`
          field_right=`echo $result|sed  -n 's/{\(.*\),\(.*\),\(.*\)}/\3/gp'  |grep -v code|awk -F: '{print $2}'`

          if [ -n "$field_left" ] 
          then
            if [ "$field_left" -ne 0 ]
            then
              ret=$field_left
            fi
          fi

          if [ -n "$field_center" ] 
          then
            if [ "$field_center" -ne 0 ]
            then
              ret=$field_center
            fi
          fi

          if [ -n "$field_right" ] 
          then
            if [ "$field_right" -ne 0 ]
            then
              ret=$field_right
            fi
          fi
        fi
        if [ "$ret" -ne 0 ]
        then
          start_impl
          return $?
        else
          sed  -i '/^status/s/\(.*\"\)\(.*\)\(\".*\)/\1'$off'\3/g' $file
        fi

      fi
    fi 
  fi 
}
restart() {
	stop
	sleep 1
	start
	return $?
}

shutdown() {
	stop
	return $?
}

stop() {
	/usr/sbin/supervisord stop
	return $?
}

status() {
	/usr/sbin/supervisord status
	echo $?
	return $?
}
#
