#!/bin/sh
# Copyright (C) 2016 Xiaomi
# Handle usb hotplug event

. /lib/functions/block.sh

device=`basename $DEVPATH`

# We don't need noflushd for each partiton
[ "$DEVTYPE" = "disk" ] || exit 0

case "$ACTION" in
	add)
		# Skip if it's USB flashdisk
		removable=`cat /sys/$DEVPATH/removable`
		[ "$removable" = "1" ] && exit 0

		#already running?
		ps | grep noflushd | grep -q "$device"
		[ "$?" = 0 ] && exit 0

		/usr/sbin/noflushd -n 5 /dev/"$device"
		pid=`ps | grep noflushd | grep "$device" | awk '{print $1}'`
		logger -s -p 3 -t "Hotplug" "Starting noflushd ("$pid") for "$device""
		;;
	remove)
		pid=`ps | grep noflushd | grep "$device" | awk '{print $1}'`
		[ -z $pid ] && exit 0

		logger -s -p 3 -t "Hotplug" "Stop noflushd ("$pid")"
		kill $pid
		;;
esac
